server:
  port: 8080
---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: ScreeningManage
          uri: http://localhost:8081
          predicates:
            - Path=/screenings/**
        - id: HospitalManage
          uri: http://localhost:8082
          predicates:
            - Path=/hospitals/** 
        - id: ReservationManage
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/** 
        - id: MyPage
          uri: http://localhost:8084
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
#        - id: ScreeningManage
        -id : user21-screening-repo
          uri: http://ScreeningManage:8080
          predicates:
            - Path=/screenings/**
 #       - id: HospitalManage
        - id: user21-hospital-repo
          uri: http://HospitalManage:8080
          predicates:
            - Path=/hospitals/** 
#        - id: ReservationManage
        - id: user21-reservation-repo        
          uri: http://ReservationManage:8080
          predicates:
            - Path=/reservations/** 
#        - id: MyPage
        - id: user21-mypage-repo
          uri: http://MyPage:8080
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

